deploy/olm/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
manifests/local-storage-operator/0.0.8/local-storage.v0.0.8.clusterserviceversion.yaml
pkg/apis/local/v1alpha1/types.go

Since we have proper images now, we can change these locations.
cc @openshift/storage

Change location of default images to more official versions

---

README.md
docs/deploy-with-olm.md
examples/olm/catalog-create-subscribe.yaml
examples/olm/create-cr.yaml

Add docs on how to deploy using OLM

add docs for OLM deploy

---

HACKING.md
examples/olm/catalog-create-subscribe.yaml
examples/olm/create-cr.yaml
pkg/diskmaker/diskmaker.go

Add hacking docs and update existing docs

fix a bug with symlink creation

---

cmd/local-storage-operator/main.go
deploy/crd.yaml
manifests/4.2.0/local-volumes.crd.yaml
pkg/apis/local/v1/types.go
pkg/controller/controller.go
pkg/controller/controller_test.go

- Also rename managmentState key.
- Fix klog initialization when logrus is also present

Add validation

---

examples/olm/catalog-create-subscribe.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1732745

Fix example of local-registry

---

examples/olm/catalog-create-subscribe.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=1732745#c3

Fix company name

---

manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml

Fix install modes and all information.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1743482 and https://bugzilla.redhat.com/show_bug.cgi?id=1743494

Bug 1743482: Fix install modes

---

manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1743494

Bug 1743494: Add createdAd field

---

docs/deploy-with-olm.md
examples/olm/catalog-create-subscribe.yaml

Update docs to use OperatorSource
/sig storage

Update docs for local-storage-operator to use OperatorSource

---

HACKING.md
manifests/4.3/image-references
manifests/4.3/local-storage-operator.v4.2.0.clusterserviceversion.yaml
manifests/4.3/local-volumes.crd.yaml
manifests/art.yaml
manifests/local-storage-operator.package.yaml

Fixes https://github.com/openshift/local-storage-operator/issues/47

Add manifests for 4.3 version

---

examples/olm/catalog-create-subscribe.yaml
manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1766856
cc @openshift/sig-storage

Fix ocp 4 3 install

---

manifests/4.4/image-references
manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
manifests/4.4/local-volumes.crd.yaml

Fixes Dockerfile reconcile errors being triggered in build pipeline.

Add manifests for 4.4 branch

---

manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml
manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml

This is cherry pick of #61 into 4.3 branch.
/assign @gnufied

Bug 1779545: [4.3] Allow operator to be upgraded automatically when an update is available

---

manifests/local-storage-operator.package.yaml

Fixes https://github.com/openshift/local-storage-operator/issues/58

Change package version

---

manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1783835

Bug 1783835: Fix managment state displayName

---

manifests/4.2/local-storage-operator.v4.2.0.clusterserviceversion.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1782575

[4.2] Bug 1782575: restrict minimum Kube version

---

Makefile
cmd/diskmaker/diskmaker.go
cmd/local-storage-operator/main.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1744498

Bug 1744498:  Add version information to local-storage-operator

---

pkg/controller/api_updater.go
pkg/controller/controller.go
pkg/controller/controller_test.go

Ensure that daemonsets are rolled out when something in LocalVolume object changes.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1793750

Bug 1793750: Fix ds force rollout

---

pkg/controller/controller.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1788916

Bug 1788916: Blocking owner deletion should prevent LocalObject from disappearing

---

manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
manifests/4.5/local-storage-operator.v4.5.0.clusterserviceversion.yaml

Bug 1802976: Fix typo

---

manifests/4.5/local-storage-operator.v4.5.0.clusterserviceversion.yaml

Also fixes skipRange version substitution

Bug 1813115 and Bug 1770183: Fix version being displayed in UI

---

manifests/4.5/local-storage-operator.v4.5.0.clusterserviceversion.yaml

This fixes version mismatch when comparing skipRange string.

Fix quote around version

---

manifests/4.6/image-references
manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
manifests/4.6/local-volumes.crd.yaml
manifests/local-storage-operator.package.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1843008

Bug 1843008: Create manifests for 4.6 channels

---

manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1779545

Bug 1779545: Use double quote for matching skiprange

---

pkg/diskmaker/diskmaker.go

This includes additional error messages if the LocalVolume CR contains invalid data. For instance, if it points to an entry that isn't in `/dev/<disk>` or if there's a file in the path specified that isn't the expected device.

Bug 1840127: Enhanced error message reporting

---

manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml

so as it can match same string in art.yaml

Bug 1850090: [4.4] Use double quotes for skipRange

---

go.sum
pkg/diskmaker/diskmaker.go

fixing a tiny bug where the wrong error is logged.
Also helps me test if the CI is flaky only on my other PR :)

Fix bug: logging the wrong error var

---

pkg/diskmaker/diskmaker.go

Throwing away errors is not a good idea. :(

log eval symlink error if it happens

---

pkg/diskmaker/diskmaker.go
pkg/diskmaker/event_reporter.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1874048
cc @openshift/sig-storage

Bug 1874048: Prevent creation of duplicate PVs for same device

---

go.mod
go.sum

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1881625
it seems to have disappeared from internet

Bug 1881625: Replace goautoneg library

---

manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1882828

Bug 1882828: Add discovery result CR to CSV

---

pkg/diskmaker/diskmaker.go
pkg/diskmaker/event_reporter.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1882775

Bug 1882775: Prevent creation of duplicate PVs for same device

---

manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml

Bug 1884285: Fix CSV layout after previous commit

---

pkg/diskmaker/controllers/lvset/add.go
pkg/diskmaker/controllers/lvset/device_age.go
pkg/diskmaker/controllers/lvset/device_age_test.go
pkg/diskmaker/controllers/lvset/reconcile.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1884306

Bug 1884306: Cleanup code for delaying device provisioning

---

HACKING.md
examples/olm/catalog-create-subscribe.yaml

Document how to use new index image format.

Document testing using opm command

---

manifests/4.7/local-volume-discoveries.crd.yaml
manifests/4.7/local-volume-discovery-results.crd.yaml

https://github.com/openshift/local-storage-operator/pull/176 fixed only 4.6 directory, propagate the changes to 4.7 now.

Bug 1887750: Sync CRD manifests to 4.7 dir

---

pkg/diskmaker/diskmaker.go

Signed-off-by: kesavan <kvellalo@redhat.com>

Bug 1862430: Separating pv lock aquisition and symlinking from loop to a method 

---

hack/test-e2e.sh
manifests/4.7/local-volume-discoveries.crd.yaml
manifests/4.7/local-volume-discovery-results.crd.yaml

Remove duplicate fields.
See https://bugzilla.redhat.com/show_bug.cgi?id=1898839 for build errors it caused.
And fix e2e tests broken by migration to multi-stage.

Bug 1898839: Fix CRD yaml files

---

hack/test-e2e.sh
pkg/diskmaker/diskmaker.go

Fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1886383

Bug 1886383: Fix bug with device lock acquisition failing

---

hack/test-e2e.sh
pkg/diskmaker/diskmaker.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1903361

Bug 1903361: Fix bug with device lock acquisition failing

---

opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
pkg/diskmaker/controllers/lvset/reconcile.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1917678

Bug 1917678: Fix no PV being provisioned for missing dev by-id symlink

---

pkg/controller/nodedaemon/daemonsets.go
pkg/diskmaker/controllers/lvset/matcher.go
pkg/internal/diskutil.go
pkg/internal/diskutil_test.go
test/e2e/localvolumediscovery_test.go

/assign @gnufied 
We'll need a backport for this

Bug 1929175: localvolumeset should ignore disks with bind-mounts

---

HACKING.md
Makefile
hack/sync_bundle
opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml

Add commands to generate csv and bundle and index image

Add script to sync bundle

---

pkg/controller/localvolumediscovery/localvolumediscovery_controller.go
pkg/controller/nodedaemon/daemonsets.go

Includes the `rollingUpdate` DSUpdateStrategy in the diskmaker-discovery and diskmaker-manager DaemonSets.

Bug 1947779: Include maxUnavailable in DaemonSets

---

test/e2e/main_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1954687
Signed off by: Priyanka Jiandani <pjiandan@redhat.com>

Bug 1954687: Reenabled commented out e2e tests for LocalVolumeDiscovery and LocalVolumeSet

---

deploy/localvolumeset_cr.yaml
deploy/localvolumeset_cr1.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1954688
Signed-off-by: priyanka19-98 <pjiandan@redhat.com>

Bug 1954688: Added example LocalVolumeSet CR

---

must-gather/gather

Updates the LSO must-gather script to collect the logs from any LSO pods that are running.

Bug 1959699: Updated gather script to collect pod logs

---

pkg/common/provisioner_utils.go
pkg/common/storage_class_owner.go
pkg/common/storage_class_owner_test.go
pkg/controller/localvolume/add.go
pkg/controller/localvolume/reconcile.go
pkg/controller/localvolumeset/add.go
pkg/controller/localvolumeset/reconcile.go
pkg/controller/localvolumeset/status.go
pkg/controller/localvolumeset/status_test.go
pkg/diskmaker/controllers/lv/add.go
pkg/diskmaker/controllers/lv/create_pv_test.go
pkg/diskmaker/controllers/lvset/create_pv_test.go
test/e2e/cleanup_hostdirs.go
test/e2e/gomega_util.go
test/e2e/localvolume_test.go
test/e2e/localvolumeset_test.go

Added back the provisioner annotation:  pv.kubernetes.io/provisioned-by: 

Bug 1952820: Add provisioned-by annotation to PV

---

pkg/diskmaker/controllers/lvset/create_pv.go

this is done because some device-ids are not valid label values.

Bug 1963899: Move device information to annotations (backport to 4.7)

---

diskmaker/controllers/lv/reconcile.go

Bug 1994035: increase the polling interval to 1m for lv diskmaker

---

diskmaker/controllers/deleter/reconcile.go

`For()` will call `DeleteReconciler` with PVs, whose namespace is empty. This results in errors:
```
ERROR	deleter	could not get provisioner configmap	{"Request.Namespace": "", "Request.Name": "local-pv-26ba56f", "error": "ConfigMap \"local-provisioner\" not found"}
```
PVs are already processed by `Watches()` and requests will be reconciled with the correct LSO namespace. Use the deleter ConfigMap in `For()`.

Bug 2001765: deleter: Don't call reconciler with PVs

---

controllers/localvolume/localvolume_controller.go
controllers/localvolumediscovery/localvolumediscovery_controller.go
controllers/localvolumediscovery/localvolumediscovery_controller_test.go
controllers/localvolumeset/finalizer.go
controllers/localvolumeset/localvolumeset_controller.go
controllers/localvolumeset/localvolumeset_controller_test.go
controllers/localvolumeset/status.go
controllers/nodedaemon/reconcile.go
diskmaker/controllers/deleter/reconcile.go
diskmaker/controllers/lv/reconcile.go
diskmaker/controllers/lv/reconcile_test.go
diskmaker/controllers/lvset/create_pv_test.go
diskmaker/controllers/lvset/device_age_test.go
diskmaker/controllers/lvset/reconcile.go
diskmaker/controllers/lvset/reconcile_test.go
diskmaker_manager/manager.go
go.mod
localmetrics/exporter.go
main.go
vendor/modules.txt

Signed off by: Priyanka Jiandani <pjiandan@redhat.com>

Bug 2000846: Structure the logs to same format in the entire codebase 

---

deploy/rbac.yaml

Signed off by: Priyanka Jiandani <pjiandan@redhat.com>

Bug 2000837: Update RBAC api to v1 from v1beta1 (backport to 4.8)

---

controllers/localvolume/localvolume_controller.go
controllers/localvolumediscovery/localvolumediscovery_controller.go
controllers/localvolumeset/localvolumeset_controller.go
controllers/nodedaemon/reconcile.go
diskmaker/controllers/deleter/reconcile.go
diskmaker/controllers/lv/reconcile.go
diskmaker/controllers/lvset/reconcile.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2019452

Bug 2019452: Do not recursively add key/value pairs to logger objects

---

Dockerfile
Dockerfile.diskmaker
diskmaker/controllers/lv/fs_interface.go
diskmaker/controllers/lv/reconcile.go
diskmaker/controllers/lv/reconcile_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2052618
Note for reviewers:
I tested this code by disabling udev rules that create symlink in `/dev/disk/by-id` path and it seems to have worked.

Bug 2052618:Use device location specified by user for LocalVolume PV creation

---

controllers/nodedaemon/reconcile.go

ServiceMonitor `local-storage-operator-metrics` was created by LSO in 4.8 to capture metrics from LSO itself. We stopped creating the ServiceMonitor in 4.9 and LSO does not even expose the metrics port, therefore delete it.

Bug 2052071: Delete obsolete ServiceMonitor

---

diskmaker/controllers/deleter/reconcile.go

Fix https://bugzilla.redhat.com/show_bug.cgi?id=2023614
For() will call DeleteReconciler with PVs, whose namespace is empty. This
results in errors:
ERROR	deleter	could not get provisioner configmap	{"Request.Namespace": "", "Request.Name": "local-pv-26ba56f", "error": "ConfigMap \"local-provisioner\" not found"}
PVs are already processed by Watches() and requests will be reconciled with
the correct LSO namespace. Use the deleter config map in For().

Bug 2023614: deleter: Don't call reconciler with PVs

---

Dockerfile
Dockerfile.diskmaker
diskmaker/controllers/lv/fs_interface.go
diskmaker/controllers/lv/reconcile.go
diskmaker/controllers/lv/reconcile_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2061995

Bug 2061995: Use device location provided by the user

---

common/provisioner_utils.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=2061447

Bug 2061447: local pv's are in terminating state

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Bug 2067761: Bump prometheus/client_golang to v1.11.1

---

go.mod
go.sum
vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go

[release-4.7] Bug 2067699: Update to moby v20.10.14

---

go.mod
go.sum

[release-4.6] Bug 2067698: Update to moby v20.10.14

---

diskmaker/controllers/lv/fs_interface.go
diskmaker/controllers/lv/reconcile.go
diskmaker/controllers/lv/reconcile_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2105453

Bug 2105453: Node reboot causes duplicate volumes

---

pkg/diskmaker/controllers/lv/add.go
pkg/diskmaker/controllers/lv/fs_interface.go
pkg/diskmaker/controllers/lv/reconcile.go
pkg/diskmaker/controllers/lv/reconcile_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2104258

Bug 2104258: Missing PVs after upgrade to 4.8

---

Dockerfile
Dockerfile.diskmaker
Dockerfile.mustgather.rhel7
config/manifests/local-storage-operator.package.yaml
config/manifests/stable/local-storage-operator.clusterserviceversion.yaml

Bump CSV and Dockerfile images to 4.12

---

diskmaker/controllers/lv/reconcile.go

Given a LocalVolume with an non-existent devicePath (e.g., /dev/vdd):
```
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
name: example
namespace: openshift-local-storage
spec:
storageClassDevices:
- devicePaths:
- /dev/vdd
fsType: ext4
storageClassName: foobar
volumeMode: Filesystem
logLevel: Normal
managementState: Managed
``` 
The event message looks incomplete/incorrect:
```
$ oc describe localvolume/example
(...)
Events:
Type     Reason                    Age   From                            Message
----     ------                    ----  ----                            -------
Warning  ErrorFindingMatchingDisk  77s   localvolume-symlink-controller  ip-10-0-132-109.ec2.internal - unable to add disk /dev/vdd to local disk pool: lstat /dev/vdd: no such file or …
```

Bug 2053505: Remove duplicate/wrong event message when volume is not attached to node

---

config/manifests/local-storage-operator.package.yaml
config/manifests/stable/local-storage-operator.clusterserviceversion.yaml

Update csv version of LSO from 4.13 to 4.14

OCPBUGS-11807: Bump version to 4.14

---

internal/diskutil_test.go

Should resolve unit test failures in:
#402 #403 #404

OCPBUGS-12312: fix TestListBlockDevices unit test

---

api/v1alpha1/localvolumediscovery_types.go
diskmaker/controllers/lvset/matcher_test.go
diskmaker/discovery/discovery.go
diskmaker/discovery/discovery_test.go
internal/diskutil.go

This is a manual cherry-pick of https://github.com/openshift/local-storage-operator/pull/394
/assign RomanBednar

[release-4.12] OCPBUGS-13357: add multipath support for volume discovery

---

config/manifests/local-storage-operator.package.yaml
config/manifests/stable/local-storage-operator.clusterserviceversion.yaml

Increase OCP version in OLM metadata.

STOR-1590: Bump OLM metadata to 4.16

---

config/manifests/local-storage-operator.package.yaml
config/manifests/stable/local-storage-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-1606

STOR-1606: Bump OLM metadata to 4.17

---

config/manifests/local-storage-operator.package.yaml
config/manifests/stable/local-storage-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-2009
/label px-approved
/label docs-approved

STOR-2009: Bump OLM metadata to 4.18

---

config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
go.mod
go.sum
pkg/common/finalizer_util.go
pkg/common/names.go
pkg/common/provisioner_utils.go
pkg/common/symlink_utils.go
pkg/controllers/localvolume/controller_events.go
pkg/controllers/localvolume/localvolume_controller.go
pkg/controllers/localvolumeset/finalizer.go
pkg/controllers/localvolumeset/finalizer_test.go
pkg/controllers/localvolumeset/localvolumeset_controller.go
pkg/diskmaker/controllers/lv/reconcile.go
pkg/diskmaker/controllers/lvset/reconcile.go
pkg/diskmaker/event_reporter.go
test/e2e/gomega_util.go
test/e2e/localvolume_test.go
test/e2e/localvolumeset_test.go
test/e2e/symlink_check.go
test/framework/consts.go
test/framework/framework.go
vendor/modules.txt
vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/common/common.go
vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/jobcontroller.go

https://issues.redhat.com/browse/STOR-1306
https://github.com/openshift/enhancements/blob/master/enhancements/storage/cleanup-lso-symlink.md
Enhancement updates: https://github.com/openshift/enhancements/pull/1717

STOR-1306: Automate LSO symlink cleanup

---

config/manifests/local-storage-operator.package.yaml
config/manifests/stable/local-storage-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-2260

STOR-2260: Bump OLM metadata to 4.19

---

config/manifests/stable/local-storage-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-1877

STOR-1877: Run operators without root user control

---

Makefile
config/manifests/local-storage-operator.package.yaml
config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
hack/update-metadata.sh

https://issues.redhat.com/browse/STOR-2600
/cc @openshift/storage-qe

STOR-2600, OCPBUGS-61434: Bump OLM metadata to 4.21
