openshift/local-storage-operator

pkg/controller/controller.go
Because it is needed to resolve symlinks
=> We need to mount /dev in provisioner pod as well

docs/deploy-with-olm.md
This PR just fixes a couple of typos and clears up some things in the
install doc to make it a bit more explicit.
It also points out that the operator works on upstream kubernetes as
well and adds some notes about how to deploy to a 1.14 Kubernetes
cluster.
=> Fix some typos, and clarify docs

Makefile
The docker build was missing the required `.`, this patch adds it and
also while we're at it we add image push functionality.  So now set 
REGISTRY env variable appropriately and do:
`make images` to build images, and `make push-images` to push the 
image to your registry.  Or, just run `make push` and do it all in one shot.
=> Fix makefile docker build and add push

HACKING.md, examples/olm/catalog-create-subscribe.yaml, manifests/4.2.0/local-volumes.crd.yaml
- Fix bug with API version.
- Delete image-references file. It appears to be the main reason for manifests not working with operator-registry
=> Move the operator examples to stable channel

hack/test-e2e.sh
Fix namespace in which e2e tests will run.
=> Use default namespace if none available

cmd/diskmaker/diskmaker.go, cmd/local-storage-operator/main.go, deploy/rbac.yaml, hack/test-e2e.sh, manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml, manifests/4.2.0/local-volumes.crd.yaml, pkg/common/types.go, pkg/controller/api_updater.go, pkg/controller/controller.go, pkg/controller/controller_events.go, pkg/controller/controller_test.go, pkg/diskmaker/api_updater.go, pkg/diskmaker/diskconfig.go, pkg/diskmaker/diskmaker.go, pkg/diskmaker/diskmaker_test.go, pkg/diskmaker/event_reporter.go, test/e2e/localstorage_test.go
This PR includes all the changes from - https://github.com/openshift/local-storage-operator/pull/33
and adds:
1. Add a finalizer to `LocalVolume` object. 
2. Add more e2e test to verify `LocalVolume` state and finalizers.
3. Enable `LocalVolume.Status` status as a subresource.
=> Add local volume finalizer

cmd/diskmaker/diskmaker.go, deploy/rbac.yaml, hack/test-e2e.sh, manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml, pkg/controller/api_updater.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/diskmaker/api_updater.go, pkg/diskmaker/diskconfig.go, pkg/diskmaker/diskmaker.go, pkg/diskmaker/diskmaker_test.go, pkg/diskmaker/event_reporter.go, test/e2e/localstorage_test.go
1. Adds a `local-volume-owner` label to all created PVs by local-storage-operator for easy tracking of created PVs. 
2. Report error events from node back to localvolume CR. Make sure that events aren't spammed.
3. Do not update localvolume if already on latest version and no change.
4. Allow e2e tests to run against plain k8s.
=> Add pv ownership and diskmaker events

manifests/4.2.0/local-storage-operator.v4.2.0.clusterserviceversion.yaml
When installing via operator source, the pvc and events permissions
are granted only for local-storage namespace but local storage
provisioner requires permission at cluster scope.
/sig storage
cc @jsafrane @bertinatto
=> Fix rbac permissions when operator is installed via OperatorSource

pkg/diskmaker/diskmaker.go
Previously, if multiple devices were defined, and a node contained some of them, no error would be reported. 
This includes an event when any disk cannot be found on a node. For instance:
>   Warning  ErrorFindingMatchingDisk  2m10s  local-storage-diskmaker  ip-10-0-150-160.us-east-2.compute.internal - unable to find matching disk /dev/xvdf
>   Warning  ErrorFindingMatchingDisk  2m10s  local-storage-diskmaker  ip-10-0-150-160.us-east-2.compute.internal - unable to find matching disk /dev/xvdg
=> Added error if a disk can't be found.

manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml, manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Allow operator to be updated automatically across minor versions.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1770183
=> Bug 1770183: Allow operator to be upgraded automatically

docs/deploy-with-olm.md, pkg/apis/local/v1/types.go, pkg/controller/controller.go, pkg/controller/controller_test.go, test/e2e/localstorage_test.go
Allows a user to pass Tolerations into the LocalVolume CR, which will then be propagated to the diskmaker and provisioner DaemonSets.
I've ran the unit tests, and Tolerations are included as nil if not defined. If they are defined, then these are passed to the DaemonSets and scheduled appropriately. I tested these with and without Tolerations, and they appear to schedule the pods correctly.
This is for OCP 4.3+
=> Bug 1774278: [4.3] Include Tolerations in the LocalVolume CR.

manifests/4.3/local-volumes.crd.yaml, manifests/4.4/local-volumes.crd.yaml, pkg/apis/local/v1/zz_generated.deepcopy.go
The LocalVolume CRDs were not updated as part of https://github.com/openshift/local-storage-operator/pull/59 . This PR corrects that oversight.
=> Updating manifests to include Toleration definitions

manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml, manifests/4.4/local-volumes.crd.yaml
The operator is called "Local Storage Operator", however, it's CRD is "Local Volume", not "Local Volume operator".
And consistently mention that fields of the object affect only the object itself (and its provisioner and diskmaker), not the operator itself.
/assign @gnufied @huffmanca
=> Bug 1783857: Use Local Volume consistently for the CRD.

examples/olm/catalog-create-subscribe.yaml, manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Allow installation of local-storage-operator in a single namespace.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1784320
=> Bug 1784320: Fix install-mode for local-storage operator

manifests/4.4/image-references, manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml, manifests/4.4/local-volumes.crd.yaml, manifests/local-storage-operator.package.yaml
Restore 4.4 manifests for now, because we are still syncing master changes into 4.4 release automatically.
cc @sosiouxme
=> Bug 1798198: We need to keep 4.4 channels for now

manifests/4.2/local-storage-operator.v4.2.0.clusterserviceversion.yaml, manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml, manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1782574
=> [4.3] Bug 1782574: Restrict minimum kube version

pkg/controller/controller.go, pkg/controller/controller_events.go, test/e2e/localstorage_test.go
This is a follow up to https://github.com/openshift/local-storage-operator/pull/85. 
Delete storageclass when localvolume object is deleted without using ownerreferences.
=> Bug 1800637: Remove orphan storageclasses

docs/deploy-with-olm.md
We should warn people from using docs stored in github repo, so as we do not have issues like https://github.com/openshift/local-storage-operator/issues/87
=> Warn about installation on OCP from in-tree docs

pkg/controller/controller.go, pkg/controller/controller_events.go, test/e2e/localstorage_test.go
Fix removal of children objects.
=> Bug 1803215:Prevent deletion of children objects owned by LocalVolume object

manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1817826 
this is cherry-pick of https://github.com/openshift/local-storage-operator/pull/96 for 4.4 branch.
=> Bug 1817826: Fix automatic upgrade of LSO

manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml, manifests/art.yaml
This should allow operator to be updatable automatically.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1779545
This is just a reworked cherry-pick of https://github.com/openshift/local-storage-operator/pull/99
=> Bug 1779545: Fix skipRange for 4.3

manifests/4.3/local-storage-operator.v4.3.0.clusterserviceversion.yaml, manifests/4.4/local-storage-operator.v4.4.0.clusterserviceversion.yaml
We currently use digests for 4.4 and 4.5; however, because we specify the versions instead of relying on the `olm.skipRange` to subscribe to the correct channel. Changing this to be `latest` should allow ART to correctly use the digest instead of the tag.
=> Bug 1781502: Updating LSO to use digest for 4.3

README.md, docs/deploy-with-olm.md
This addresses [issue 77](https://github.com/openshift/local-storage-operator/issues/77), and corrects the version of OCP 4.2 reported in the README and docs.
=> Corrected version to 4.2

manifests/4.5/local-volumes.crd.yaml
Kubernetes structural schema requires type of all fields and array items. In addition, it does not know "dateTime" type.
/assign @gnufied
=> Bug 1826185: Fix status.conditions type

manifests/4.5/local-volumes.crd.yaml
`type` is a mandatory field. Adding `description` for completeness.
=> Bug 1826185: Add root type and description

pkg/controller/controller.go, pkg/controller/controller_events.go, test/e2e/localstorage_test.go
Currently children of `LocalVolume` can be incorrectly GCed if `LocalVolume` object can't be found because of temporary api-server issues.
=> Bug 1803216: Prevent unwanted deletion of children when LocalVolume can't be found

pkg/controller/api_updater.go, pkg/controller/controller.go, pkg/controller/controller_test.go
It was noticed in [BZ1822213](https://bugzilla.redhat.com/show_bug.cgi?id=1822213) that the diskmaker and provisioner pods are not updated when the local storage operator is.
This PR adds the controller version into the configmaps. When the version changes the diskmaker and provisioner pods will be redeployed.
=> Bug 1822213: Include version in diskmaker and provisioner configmap

manifests/4.5/local-volumes.crd.yaml
Before:
```
KIND:     LocalVolume
VERSION:  local.storage.openshift.io/v1
DESCRIPTION:
<empty>
```
After:
```
KIND:     LocalVolume
VERSION:  local.storage.openshift.io/v1
DESCRIPTION:
LocalVolume is a local storage configuration used by the operator
FIELDS:
apiVersion   <string>
APIVersion defines the versioned schema of this representation of an
object. Servers should convert recognized schemas to the latest internal
value, and may reject unrecognized values. More info:
https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
kind <string>
Kind is a string value representing the REST resource this object
represents. Servers may infer this from the endpoint the client submits
requests to. Cannot be updated. In CamelCase. More info: …
```
=> Bug 1836931: Ensure that LocalVolume objects use structured schema

docs/deploy-with-olm.md, examples/olm/catalog-create-subscribe.yaml, examples/olm/redhat-src-catalog.yaml, manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
This will change namespace of local-storage-operator from `local-storage` to `openshift-local-storage`. In general this should fine. The clusters which are using LSO in `local-storage` namespace will keep working in that namespace even after upgrade, we make no attempt to move the operator back into `openshift-local-storage` namespace. 
With OLM the operator's namespace is anyways an suggestion and not something we can enforce. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1840319
=> Bug 1840319: Change namespace of local-storage operator

manifests/4.5/local-storage-operator.v4.5.0.clusterserviceversion.yaml
We need to update skipVersion in 4.5 so as the operator can update itself. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1850143
I am making this fix because https://github.com/openshift/local-storage-operator/pull/117 PR did not make it to `release-4.5` branch.
=> Bug 1850143: Fix quote in 4.5 version so as it can automatically update

pkg/diskmaker/discovery/discovery.go, pkg/diskmaker/discovery/discovery_test.go, pkg/internal/diskutil.go, pkg/internal/diskutil_test.go
The PR fixes LocalVolumeDiscovery to discover devices with `PARTLABEL`  as `BIOS-BOOT` and `EFI-SYSTEM` as `Unavailable`. 
=> Bug 1867066: [Auto-discovery] List BIOS-BOOT and EFI-SYSTEM devices as Unavailable

Dockerfile.mustgather, Dockerfile.mustgather.rhel7, Makefile, README.md, docs/must-gather.md, must-gather/gather
This PR adds a script and corresponding image to work with `oc adm must-gather`. This will cycle through all of the CRDs and output any resources for them.
=> Bug 1756096: Included must-gather script and image

manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
This was a leftover from a feature we decided to forgo.
=> Bug 1868365: Remove spec.minDeviceCount from LocalVolumeSet CSV example

deploy/rbac.yaml, manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
Dynamic RBAC was removed in #110, so this is no longer necessary.
=> Bug 1862443: Remove permission to modify serviceaccounts

test/e2e/localvolumediscovery_test.go
e2e tests for localvolumediscovery fails randomly while verifying the discovery results. Made wait.PollImmediateto to retry if discovery result CR is not found.
=> Bug 1872599: fix e2e tests for localvolumediscovery

manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
alm-example for LocalVolumeSet should use `deviceMechanicalProperties` instead of `deviceMechanicalProperty`
=> BUG 1874695: fix alm-examples in 4.6 csv file

cmd/diskmaker/diskmaker.go, cmd/manager/main.go
Operator-sdk changes broke the local-storage-operator version reporting. This PR fixes that and shows correct local-storage-operator version
=> BUG 1875060:  show correct local-storage-operator version

manifests/4.6/local-volumes.crd.yaml
fsType should be empty when volumeMode is Block.
=> Bug 1876743: Add note about fsType value

deploy/rbac.yaml, manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml, pkg/controller/localvolumediscovery/localvolumediscovery_controller.go, pkg/controller/localvolumediscovery/localvolumediscovery_controller_test.go, pkg/diskmaker/discovery/discovery_test.go, pkg/diskmaker/discovery/sync_result.go
LocalVolumeDiscovery CR uses ownerrefernce>kind as LocalVolumeDisovery but uses the ownerrefernce UUID of daemonset POD
This PR changes the owner references of the LocalVolumeDiscoveryResult objects to LocalVolumeDiscovery object. The reconcile method deletes the orphan results on every run. 
=>  BUG 1869497:   fix invalid ownerrefernce for localvolumediscoveryresult CR

pkg/apis/local/v1alpha1/localvolumediscovery_types.go, pkg/apis/local/v1alpha1/localvolumediscoveryresult_types.go, pkg/diskmaker/discovery/discovery.go, pkg/diskmaker/discovery/discovery_test.go
Local volume discovery is only discovering `disk` and `partition` device type. This PR adds support for discovering `lvm` device types as well. 
=> Bug 1862610: discover lvm devices in LocalVolumeDiscovery

pkg/controller/localvolumediscovery/localvolumediscovery_controller.go, pkg/diskmaker/discovery/discovery.go, pkg/internal/diskutil.go, pkg/internal/diskutil_test.go
Continuous discovery changes the device status to NotAvailable when pv is provisioned on it.
In case of filesystem mode pv, the discovery checks the filesystem on the device and makes it NotAvailable.
For block mode pv, the discovery checks the bind mount of the device in /var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/<pv-name>/<pod-uuid>
and makes the device as NotAvailable if a bind mount is present.
=> BUG 1872079: change device status to NotAvailable if block mode pv is provisioned on it.

pkg/common/names.go, pkg/common/volume_definitions.go, pkg/controller/localvolumediscovery/localvolumediscovery_controller.go, pkg/controller/nodedaemon/add.go, pkg/controller/nodedaemon/daemonsets.go, pkg/controller/nodedaemon/provisioner_config.go, pkg/controller/nodedaemon/reconcile.go, pkg/diskmaker/controllers/lvset/reconcile.go
Mounting `/run/udev` to allow lsblk to detect the FSType of lvm disks as `LVM2_member`
Verification:
```
$ oc debug node/$MY_NODE_NAME  -- chroot /host lsblk -o +FSTYPE
Starting pod/ip-10-0-162-216us-east-2computeinternal-debug ...
To use host binaries, run `chroot /host`
NAME                         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT FSTYPE
nvme0n1                      259:0    0   120G  0 disk            
|-nvme0n1p1                  259:1    0   384M  0 part /boot      ext4
|-nvme0n1p2                  259:2    0   127M  0 part /boot/efi  vfat
|-nvme0n1p3                  259:3    0     1M  0 part            
`-nvme0n1p4                  259:4    0 119.5G  0 part            crypto_LUKS
`-coreos-luks-root-nocrypt 253:0    0 119.5G  0 dm   /sysroot   xfs
nvme1n1 …
```
=> Bug 1862489:  LSO autoprovisioning should exclude top level disks that are part of LVM volume group

Makefile
This breaks the build on ppc64le, which depends on the external linker
and therefore behaves differently than other architectures.
=> Bug 1884285: Do not link with -extldflags "-static"

pkg/diskmaker/discovery/discovery_test.go, pkg/diskmaker/discovery/monitor_test.go, pkg/diskmaker/discovery/sync_result_test.go, pkg/internal/diskutil.go, pkg/internal/diskutil_test.go
lsblk, sometimes, reports stale fstype information. Using blkid to fetch fstype information for the devices
=> Bug 1882630: fix stale lsblk output

manifests/4.7/image-references, manifests/4.7/local-storage-operator.v4.7.0.clusterserviceversion.yaml, manifests/4.7/local-volume-discoveries.crd.yaml, manifests/4.7/local-volume-discovery-results.crd.yaml, manifests/4.7/local-volume-sets.crd.yaml, manifests/4.7/local-volumes.crd.yaml, manifests/local-storage-operator.package.yaml, opm-bundle/bundle.Dockerfile, opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml, opm-bundle/manifests/local-volume-discoveries.crd.yaml, opm-bundle/manifests/local-volume-discovery-results.crd.yaml, opm-bundle/manifests/local-volume-sets.crd.yaml, opm-bundle/manifests/local-volumes.crd.yaml, opm-bundle/metadata/annotations.yaml
This PR adds resources for using operator-registry to build index images using new format.
It also fixes build failures for 4.7
=> Add opm resources and fix 4.7 build

OWNERS
Subcomponent is a mandatory field in Bugzilla, make sure whoever parses OWNERS can actually file a bug.
=> Add BZ subcomponent to OWNERS

manifests/4.6/local-volume-discoveries.crd.yaml, manifests/4.6/local-volume-discovery-results.crd.yaml
1. They can be potentialy dangerous - an unknown field in an old version
may have a value that won't be valid once the field is introduced.
2. It makes the schema "structural schema" that's understood by `kubectl
explain`.
Also, make `LocalVolumeDiscovery.Spec` mandatory and set `type: object`.
Neither of them have any special effect on `oc explain`, but keep the
objects nice and tidy.
=> Bug 1887750: Bug 1887751: Don't preserve unknown fields in CRs

pkg/diskmaker/controllers/lvset/reconcile.go, pkg/diskmaker/diskmaker.go
QE claimed these events may cause confusion if there is only one LocalVolume or LocalVolumeSet.
https://bugzilla.redhat.com/show_bug.cgi?id=1887046
=> Bug 1887046: Remove unnecessary events

manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml, manifests/4.7/local-storage-operator.v4.7.0.clusterserviceversion.yaml, opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
Adds the LocalVolumeDiscoveryResult CRD to the list of internal objects, preventing it from being displayed in the UI.
=> Bug 1886973: Hide the LocalVolumeDiscoveryResult CRD from the UI

pkg/diskmaker/discovery/discovery_test.go, pkg/diskmaker/discovery/monitor_test.go, pkg/diskmaker/discovery/sync_result_test.go, pkg/internal/diskutil.go, pkg/internal/diskutil_test.go
lsblk, sometimes, reports stale fstype information. Using blkid to fetch fstype information for the devices
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1885700
=> Bug 1885700: fix stale lsblk output

pkg/diskmaker/diskmaker.go, pkg/diskmaker/diskmaker_test.go, pkg/diskmaker/event_reporter.go
If the device provided in the `devicePaths` list in the localVolume CR has `/dev/disk/by-id`, then use the `id` name to create symlink in `/mnt/local-storage/<storageClassName>` directory. 
for example: `/mnt/local-storage/belowsixty/ata-VBOX_HARDDISK_____VB3ec86ebf-ed3a5a93`
Test:
1. /dev/sdb and /dev/sdc had /disk/by-id. So symlinks created by id
/dev/sdd had no id. So Symlink got created by disk name
```
/mnt/local-storage/belowsixty
$ ls
ata-VBOX_HARDDISK_____VB3ec86ebf-ed3a5a93  ata-VBOX_HARDDISK_____VBddf003e5-4cfb17c1  sdd
```
2. Triggering warning events when device has no id
```
$ kubectl get event | grep  localvolume/example
16s         Normal    FoundMatchingDisk         localvolume/example                           minikube - found matching disk /dev/sdc with id …
```
=> use /disk/by-id name as symlink name in LocalVolume

deploy/localvolume_crd.yaml, deploy/localvolumediscovery_crd.yaml, deploy/localvolumediscoveryresult_crd.yaml, deploy/localvolumeset_crd.yaml, manifests/4.7/local-storage-operator.v4.7.0.clusterserviceversion.yaml, manifests/4.7/local-volume-discoveries.crd.yaml, manifests/4.7/local-volume-discovery-results.crd.yaml, manifests/4.7/local-volume-sets.crd.yaml, manifests/4.7/local-volumes.crd.yaml, opm-bundle/manifests/local-volume-discoveries.crd.yaml, opm-bundle/manifests/local-volume-discovery-results.crd.yaml, opm-bundle/manifests/local-volume-sets.crd.yaml, opm-bundle/manifests/local-volumes.crd.yaml
updated LSO crds in /manifests/4.7 directory to use `apiextensions.k8s.io/v1` instead of `apiextensions.k8s.io/v1beta1`
The `CustomResourceDefinition` API type is promoted to `apiextensions.k8s.io/v1` with the following changes:
* Use of the new `default` feature in validation schemas is limited to v1
* `spec.scope` is no longer defaulted to `Namespaced` and must be explicitly specified
* `spec.version` is removed; use `spec.versions` instead
* `spec.validation` is removed; use `spec.versions[*].schema` instead
* `spec.subresources` is removed; use `spec.versions[*].subresources` instead
* `spec.additionalPrinterColumns` is removed; use `spec.versions[*].additionalPrinterColumns` instead
*  In `additionalPrinterColumns` items, the `JSONPath` field was renamed to `jsonPath` (fixes …
=> Bug 1906519: update crds in 4.7 to use apiextensions.k8s.io/v1

manifests/4.7/local-volume-sets.crd.yaml, opm-bundle/manifests/local-volume-sets.crd.yaml, pkg/apis/local/v1alpha1/localvolumediscovery_types.go, pkg/apis/local/v1alpha1/localvolumeset_types.go, pkg/diskmaker/controllers/lvset/matcher.go, pkg/diskmaker/controllers/lvset/matcher_test.go, pkg/diskmaker/discovery/discovery.go
LocalVolumeSet doesn't cover all the possible cases to ignore boot devices and hence create
PVs on them. This PR keeps default minSize to 1Gi so that boot devices can be ignored. User can override the minSize value from the CR. Also ignore device where partlabel contains substring "boot"
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1897050
=> Bug 1897050: localVolumeSet: keep default MinSize to 1Gi and ignore devices with `boot` substring in the partLabel

hack/test-e2e.sh, manifests/4.6/local-storage-operator.v4.6.0.clusterserviceversion.yaml
This is a cherrypick of https://github.com/openshift/local-storage-operator/pull/177 for 4.6.
Adds the LocalVolumeDiscoveryResult CRD to the list of internal objects, preventing it from being displayed in the UI.
=> Bug 1904577: Hide the LocalVolumeDiscoveryResult CRD from the UI

pkg/controller/nodedaemon/reconcile.go, pkg/diskmaker/controllers/lvset/create_pv.go, pkg/diskmaker/controllers/lvset/create_pv_test.go
- Fix: PV hashing had a slight difference causing duplicate PVs (full path was being hashed as opposed to only file name in 4.6)
- Perform a one-time cleanup of the old daemonset if it exists.
=> Bug 1917315: delete localvolumeset-local-provisoner daemonset and fix PV name hashing

pkg/internal/diskutil.go, pkg/internal/diskutil_test.go
using strings.Trimspace() on all `lsblk` outputs to prevent showing local volume discovery with whitespaces.  For example, the `model` in the below discovery results shows whitespace.
```
deviceID: /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol0aae98a99ce01086e
fstype: ""
model: 'Amazon Elastic Block Store              '
path: /dev/nvme1n1
property: NonRotational
serial: vol0aae98a99ce01086e
size: 2147483648
status:
state: Available
type: disk
vendor: ""
discoveredTimeStamp: "2021-03-10T01:39:50Z"
```
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1937244
=> Bug 1937244: remove leading and trailing whitespaces in lsblk output

Dockerfile, Dockerfile.diskmaker, Dockerfile.mustgather, Dockerfile.mustgather.rhel7
Updates must-gather Dockerfiles to be more easily built for quay mirroring. There have been issues with mirroring the must-gather image to quay.io due to the current Dockerfiles. These changes allow the must-gather images to more closely mirror the OCS must-gather images, and should allow them to be mirrored to quay without issue.
=> Updates must-gather Dockerfiles to be more easily built for quay mirroring

pkg/controller/localvolume/resourceapply.go
Users might want to manually expand the PVs and hence allow volume expansion for local-storage storageclass.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1915732
cc @openshift/sig-storage
=> Bug 1915732: allow users to change allowVolumeExpansion

Dockerfile.mustgather, Dockerfile.mustgather.rhel7
I've removed the trailing `/must-gather` in the WORKDIR for the must-gather image.
@yselkowitz ,
Would you mind reviewing this? I'm a little confused, as this doesn't seem to affect my local builds and testing. I can see the `gather` binary included and executable with and without this change whenever I build it locally.
=> Corrects the WORKDIR of the must-gather image

deploy/operator.yaml, manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml, opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml, pkg/controller/nodedaemon/daemonsets.go
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
=> Add management workload annotations

deploy/operator.yaml, manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml, opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml, pkg/controller/localvolumediscovery/localvolumediscovery_controller.go, pkg/controller/nodedaemon/daemonsets.go
This pull request explicitly set the imagePullPolicy to IfNotPresent
fixes  [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1947774)
=> Bug 1947774: fix imagePullPolicy to ifNotPresent

pkg/internal/diskutil.go
Updates the way lock acquisition throws an error
=> Bug 1946497: Updates the way lock acquisition throws an error

deploy/operator.yaml, manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml, opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml, pkg/controller/nodedaemon/daemonsets.go
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
=> Rename workload annotations

deploy/rbac.yaml, manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml
This PR added permissions to operators service monitoring, allowing cluster version upgrade.
Currently the operators has `create` permission. When upgrading the cluster, it needs permission to `update` the service role.
=> Bug 1961120: added permissions to service monitoring

must-gather/gather
Continues https://github.com/openshift/local-storage-operator/pull/236 and also stores pod information in a subdirectory.
=> Bug 1959699: Adjusts command used to get pod information

pkg/diskmaker/diskmaker.go, pkg/diskmaker/diskmaker_test.go, pkg/diskmaker/event_reporter.go
If the device provided in the `devicePaths` list in the localVolume CR has `/dev/disk/by-id`, then use the `id` name to create symlink in `/mnt/local-storage/<storageClassName>` directory. 
(cherry picked from commit 7b64dc238138a1fe54f864df211fdf5eca96ed14)
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1955862
Tests:
1. Localvolume CR 
```
storageClassDevices:
- storageClassName: "test"
volumeMode: Filesystem
fsType: ext4
devicePaths:
- /dev/sdb
- /dev/sdc
- /dev/sdd
```
2. `/dev/sdd` has no diskID, where as , `/dev/sdb` and `/dev/sdc` have diskID in `/dev/disk/by-id`
```
$ ls -lR /dev/disk
/dev/disk/by-id:
total 0
lrwxrwxrwx 1 root root  9 May 17 06:54 ata-VBOX_CD-ROM_VB0-1a2b3c4d__ -> ../../sr0
lrwxrwxrwx 1 root root  9 May 17 …
```
=> Bug 1961942: use /disk/by-id name as symlink name

must-gather/gather
We use the lsoNamespace variable when storing the data, but I didn't correct it in the retrieval to allow for situations where LSO is installed in a non-default namespace.
=> Bug 1959699: Use correct namespace for must-gather

manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml, opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
PR #230 added annotations
required for supporting the workload partitioning feature for ocp 4.8.
However, OLM has a bug in processing the annotations (BZ 1950047).
This PR provides a workaround necessary to release the workload
partitioning in OCP 4.8.
=> Bug 1966561: add OLM bug workaround for workload partitioning

manifests/4.8/local-storage-operator.v4.8.0.clusterserviceversion.yaml, pkg/common/daemonsets_utils.go, pkg/controller/nodedaemon/daemonsets.go
This PR assign **openshift-user-critical** priority class to operator's pods
=> Bug 1967444: Add openshift-user-critical priority class

diskmaker/discovery/discovery.go
s/persisent/persistent
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>
=> diskmaker: discovery: fix typo in warning message

config/manifests/4.9/prometheus-role-binding.yaml, config/manifests/4.9/prometheus-role.yaml, config/rbac/diskmaker/role_binding.yaml, config/rbac/monitoring/prometheus_role.yaml, config/rbac/monitoring/prometheus_role_binding.yaml, config/rbac/role_binding.yaml
Some RBAC manifests use v1beta1 api, which is deprecated. This commit updates the api version to v1.
Signed off by: Priyanka Jiandani<pjiandan@redhat.com>
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1995653
=> Bug 1995653: Update RBAC api to v1 from v1beta1

diskmaker/controllers/lv/reconcile.go
LocalVolume device paths are explicitly specified, so if they are
already claimed, we should not fail siliently.
=> Bug 1997122: localvolume: add event/log message if device already claimed

config/manifests/4.9/prometheus-role-binding.yaml, config/manifests/4.9/prometheus-role.yaml
using `openshift-local-storage` namespace in prometheus rbac manifests fails to emit lso metrics in other namespaces.
This PR removes the namespace field from the prometheus-role-binding.yaml and prometheus-role.yaml. This enables
creating these resources in the same namespace as csv.
=> Bug 1985082: remove hard coded namespace from prometheus rbac rules

diskmaker/controllers/deleter/reconcile.go, diskmaker/controllers/lvset/reconcile.go
Don't sleep in the informer threads. When multiple PVs are released at the same time, one PV is processed in every 10 seconds. This further adds up with PV updates and it may take several minutes (hours!) to process all released PVs.
=> Bug 2001605: Don't block informer threads

diskmaker/controllers/deleter/reconcile.go, diskmaker/controllers/lvset/reconcile.go
Don't sleep in the informer threads. When multiple PVs are released at the
same time, one PV is processed in every 10 seconds. This further adds up
with PV updates and it may take several minutes to process all released
PVs.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2007684
=> Bug 2007684: Don't block informer threads [4.9]

diskmaker/controllers/lvset/reconcile.go
When multiple lvsets are created, lso_lvset_provisioned_PV_count metric uses the same value across all the storage classes.
This PR fixes this issue.
Tests:
- Total PVs provisioned: 
``` 
kubectl get pv
NAME               CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
local-pv-8ec5067   10Gi       RWO            Delete           Available           lvs1                    11m
```
- Updated metrics:
```
sh-4.4# curl http://0.0.0.0:8383/metrics | grep lso_lvset_provisioned_PV_count{
lso_lvset_provisioned_PV_count{nodeName="minikube",storageClass="lvs1"} 1
lso_lvset_provisioned_PV_count{nodeName="minikube",storageClass="lvs2"} 0
```
Adding more disks:
- Total Pvs provisioned:
```
Every 2.0s: kubectl get pv …
```
=> Bug 1993973 : fix lso_lvset_provisioned_PV_count for multiple lvset

diskmaker/controllers/lv/reconcile.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2010174
=> Bug 2010174: Fix duplicate PVs for disk by-names

config/manifests/art.yaml
Recent PR https://github.com/openshift/local-storage-operator/pull/287 introduced a filename change which is breaking ART builds. This is to make that change consistent with what's in art.yaml
cc @priyanka19-98 @yselkowitz
=> Update csv filename in art.yaml

HACKING.md, assets/templates/diskmaker-discovery-daemonset.yaml, assets/templates/diskmaker-manager-daemonset.yaml, common/daemonsets_utils.go, common/volume_definitions.go, controllers/localvolumediscovery/localvolumediscovery_controller.go, controllers/nodedaemon/daemonsets.go
This is a follow-up to the discussion in this PR:
https://github.com/openshift/local-storage-operator/pull/249#discussion_r673317023
I spent some time testing https://github.com/openshift/local-storage-operator/pull/263 (rebased on latest master branch) on vanilla k8s, but ultimately LSO support for vanilla k8s seems like a losing battle. It's a bit too much of a time sink without much benefit, and it will easily be broken again if we don't test upstream regularly. We may as well lean into the openshift dependency, and move our static resources into yaml to simplify the code as Hemant suggested.
CodeReady Containers (https://developers.redhat.com/products/codeready-containers/overview) are useful for testing LSO changes locally, along with the OpenShift instructions in HACKING.md.
/cc …
=> Move static resources into yaml assets

HACKING.md, controllers/localvolumediscovery/localvolumediscovery_controller.go
PR contains two commits, one for documenting how to run LSO locally which can be useful for verification of some bug fixes (like this one) and second with an actual fix.
=> Bug 2028685: LSO repeatedly reports errors while diskmaker-discovery pod is starting

assets/templates/diskmaker-discovery-daemonset.yaml, assets/templates/diskmaker-manager-daemonset.yaml, controllers/localvolumediscovery/localvolumediscovery_controller.go, controllers/nodedaemon/daemonset_test.go, controllers/nodedaemon/daemonsets.go
This fixes a regression caused by #298, causing the origin image to be used even in productized builds regardless of the CSV.
/cc @dobsonj
/assign @gnufied
=> Bug 2033750: Get kube-rbac-proxy from CSV

diskmaker/discovery/sync_result.go, diskmaker/discovery/sync_result_test.go
LSO was using a maximum limit of 63 character for a discovery result name before hashing the hostname. This PR ups the limit to 253 characters before hashing, keeping the hostname portion of the discovery results name more readable.
=> Bug 1950827: Updated truncate function to extend length before hashing

pkg/diskmaker/controllers/lv/reconcile.go
This is a backport of #275 to 4.8
=> Bug 2006698: increase the polling interval to 1m for lv diskmaker

config/manifests/4.10/local-storage-operator.clusterserviceversion.yaml
Need to remove the trailing comma to pass operator-sdk validator check.
This check is planned to be run in CI.
=> Bug 2041620: bundle CSV alm-examples does not parse

config/manifests/4.9/local-storage-operator.v4.9.0.clusterserviceversion.yaml
Need to remove the trailing comma to pass operator-sdk validator check.
This check is planned to be run in CI.
=> Bug 2044782: [4.9] bundle CSV alm-examples does not parse

opm-bundle/manifests/local-storage-operator.clusterserviceversion.yaml
Need to remove the trailing comma to pass operator-sdk validator check.
This check is planned to be run in CI.
=> Bug 2044783: [4.8] bundle CSV alm-examples does not parse

controllers/localvolumeset/status.go
Return `reconcileError` from `addAvailabilityConditions` to stop enqueing LocalVolumeSet after NotFound error.
`reconcileError` should be already `nil` if related LocalVolumeSet does not exist, unless something serious happened when cleaning up the object (and in that case requeue is expected).
=> Bug 2012111: Stop enqueing LocalVolumeSet after NotFound error

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2032924
This updates the vendor directory to pull in the rebase and fix from https://github.com/openshift/sig-storage-local-static-provisioner/pull/38
/cc @gnufied @jsafrane
=> Bug 2032924: PVs are not being cleaned up after PVC deletion

config/manifests/4.11/local-storage-operator.clusterserviceversion.yaml
in the OperatorHub.
Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>
=> Add label for ARM to display local storage operator

config/bundle.Dockerfile
Ran into this issue in https://github.com/openshift/release/pull/26479
It's easy to reproduce locally too. The manifests moved to 4.11 but bundle.Dockerfile needs to be updated to point to the right location.
=> Update bundle.Dockerfile to use 4.11 manifests

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2052756
This updates the vendor directory to pull in the rebase and fix from https://github.com/openshift/sig-storage-local-static-provisioner/pull/39
=> Bug 2052756: [4.10] PVs are not being cleaned up after PVC deletion

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2052757
This updates the vendor directory to pull in the rebase and fix from https://github.com/openshift/sig-storage-local-static-provisioner/pull/40
=> Bug 2052757: [4.9] PVs are not being cleaned up after PVC deletion

must-gather/gather
Simplifying must-gather collection:
`oc adm inspect namespace/<ns>` will collect all "well known" namespaced objects, like DaemonSets and Deployments, together with all pod logs.
`oc adm inspect <crd name> --all-namespaces` will then collect all CRs. 
stdout:
```
Gathering data for ns/openshift-local-storage...
Wrote inspect data to must-gather/.
Gathering data for CRD localvolumediscoveries.local.storage.openshift.io
Wrote inspect data to must-gather/.
Gathering data for CRD localvolumediscoveryresults.local.storage.openshift.io
Wrote inspect data to must-gather/.
Gathering data for CRD localvolumes.local.storage.openshift.io
Wrote inspect data to must-gather/.
Gathering data for CRD localvolumesets.local.storage.openshift.io
Wrote inspect data to must-gather/.
```
Resulting files:
```
. …
```
=> Bug 2059840: Use oc adm inspect to gather everything

config/manifests/4.11/local-storage-operator.clusterserviceversion.yaml
Adding disconnected annotation, this operator should not require an internet connection to provision local storage.
https://bugzilla.redhat.com/show_bug.cgi?id=1984785
=> Bug 1984785: LSO CSV does not contain disconnected annotation

go.mod, go.sum, vendor/modules.txt
Both moby and goautoneg are listed in go.mod via a replace directive, but they are no longer necessary.
Moby was added there because it used to be a dependency for helm, which was a dependency for operator-sdk.
Goautoneg was added there to override the one specified in library-go's go.mod file (which was invalid).
CC @openshift/storage
=> Remove unused dependencies from go.mod

go.mod, go.sum, vendor/modules.txt
Both moby and goautoneg are listed in go.mod via a replace directive, but they are no longer necessary.
Moby was added there because it used to be a dependency for helm, which was a dependency for operator-sdk.
Goautoneg was added there to override the one specified in library-go's go.mod file (which was invalid).
CC @openshift/storage
=> [release-4.10] Bug 2067702: Remove unused dependencies from go.mod

go.mod, go.sum, vendor/modules.txt
This is a backport of https://github.com/openshift/local-storage-operator/pull/340.
CC @openshift/storage
=>  [release-4.9] Bug 2067701: Remove unused dependencies from go.mod

hack/test-e2e.sh, test-framework/context.go, test-framework/context_test.go, test-framework/framework.go, test-framework/resource_creator.go, test-framework/resource_creator_test.go, test/e2e/aws_disks.go, test/e2e/cleanup_hostdirs.go, test/e2e/localvolume_test.go, test/e2e/localvolumediscovery_test.go, test/e2e/localvolumeset_test.go, test/e2e/main_test.go
This PR:
- Removes the code that generates custom install manifests during the e2e tests. We really don't need to maintain separate manifests and associated code to do that. The install is already handled by OLM (see https://github.com/openshift/release/pull/26479 for how the operator gets installed now).
- Removes some misc dead code. For example, there were some comments to remove `namespace` from context.go, and that field was set to the same value as `operatorNamespace` anyway. So I just removed that chunk of code and updated the callers to use `GetOperatorNamespace` instead of `GetNamespace`.
- Sets the default namespace to `openshift-local-storage`, where OLM installs the operator.
- Sets the `ServiceAccountName` field in `cleanup_hostdirs.go` to resolve a [test …
=> Bug 2060532: LSO e2e tests are run against default image and namespace

assets/templates/diskmaker-discovery-daemonset.yaml, assets/templates/diskmaker-manager-daemonset.yaml, config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=2077797
I followed [this guide](https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits) to measure resource usage of the LSO and diskmaker pods.
CPU:
```
scalar(
max(kube_pod_container_resource_requests{namespace="openshift-sdn", container="sdn", resource="cpu"}) / max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="openshift-sdn", container="sdn"}[120m]))) *
max by (pod, container) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="openshift-local-storage"})
```
results: 5m - 10m
MEM:
(this query is a bit different, the one from the guide wasn't working)
```
sum( container_memory_working_set_bytes{container="", …
```
=> Bug 2077797: LSO pods do not have any resource requests

api/v1alpha1/localvolumeset_types.go, config/manifests/stable/local-volume-sets.crd.yaml, config/rbac/diskmaker/role.yaml, diskmaker/discovery/discovery.go
Add support for multipath device types.
Please note, by default only "disk" type is supported but following CR can provision mpath volumes:
```
spec:
deviceInclusionSpec:
deviceTypes:
- disk
- part
- loop
- mpath
minSize: 10Mi
fsType: ext4
nodeSelector:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/hostname
operator: In
values:
- co8-tpptx-worker-9phmf
storageClassName: mpath
volumeMode: Filesystem
```
I tested and it works as expected.
=> Bug 2089387: Add multi path support for LocalVolumeSet objects

common/names.go, diskmaker/controllers/deleter/reconcile.go, diskmaker/controllers/deleter/reconcile_test.go, diskmaker/controllers/deleter/testfiles/provisioner_conf.yaml, diskmaker/controllers/lv/reconcile.go, diskmaker/controllers/lv/reconcile_test.go, diskmaker/controllers/lvset/reconcile.go, diskmaker/controllers/lvset/reconcile_test.go, test-framework/framework.go, test-framework/utils.go
cc @openshift/storage 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2091873
The patch changes PV matching in deleter reconcile loop so it will match also PVs that have node UID in the annotation, effectively ignoring the UID in the cleanup/delete flow. This is needed because node UID is not persistent and if a node gets deleted the UID changes. This can not work because reconcile tired to do exact matching and so PVs were getting stuck in Released state when UID changed.
Manually verified with following steps:
1) PV is bound (with annotation containing random UID)
```
$ oc get pv
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM           STORAGECLASS   REASON   AGE
local-pv-56c29ba0   10Gi       RWO            Delete           Bound    default/mypvc …
```
=> Bug 2091873: PVs get stuck in Released after PVC is deleted and Node UID changed

common/controller_runtime_utils.go, diskmaker/controllers/deleter/reconcile.go, diskmaker/controllers/deleter/reconcile_test.go, diskmaker/controllers/lv/reconcile.go, diskmaker/controllers/lv/reconcile_test.go, diskmaker/controllers/lvset/device_age.go, diskmaker/controllers/lvset/reconcile.go, diskmaker/controllers/lvset/reconcile_test.go, diskmaker_manager/manager.go
Introduce a new helper function - ReloadRuntimeConfig() that loads runtime config values needed for reconcile loops at one place. This should help make the code cleaner by removing copy-paste code and scattered runtime config changes.
Also adding proper constructors to reconcilers which should improve readability and ease constructing them with fakes in tests.
cc @openshift/storage
=> STOR-977: Refactor reconcilers

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Carry patch with a fix has been merged: [openshift/sig-storage-local-static-provisioner#42](https://github.com/openshift/sig-storage-local-static-provisioner/pull/42).
Bump to the fixed version and vendor.
=> OCPBUGS-2450: do not flag PV as cleaned in cache too early

.ci-operator.yaml, config/manifests/local-storage-operator.package.yaml, config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
Ref. https://issues.redhat.com/browse/ART-5087
Once configuration is bumped, the operator can be re-enabled in 4.13
=> Bump to 4.13

assets/templates/localmetrics/prometheus-rule.yaml, assets/templates/localmetrics/service-monitor.yaml, assets/templates/localmetrics/service.yaml, common/names.go, config/manifests/stable/local-storage-operator.clusterserviceversion.yaml, controllers/localvolumediscovery/localvolumediscovery_controller.go, controllers/nodedaemon/reconcile.go, localmetrics/alerts.go, localmetrics/exporter.go, localmetrics/exporter_test.go
Raise an alert when disk-manager DaemonSet has no scheduled replicas - that means either no node matched its `nodeSelector` or the nodes are tainted.
Reusing existing `kube_daemonset_status_desired_number_scheduled` metric and expecting that disk-maker DaemonSet name + namespace are fixed - the code suggests so.
=> OCPBUGS-396: Add alerts about empty DaemonSet

config/manifests/art.yaml
there is a warning reported in CVP check for 4.12
`Warning: Value : (local-storage-operator.4.12.0-202211081106) csv.metadata.Name local-storage-operator.4.12.0-202211081106 is not following the recommended naming convention: <operator-name>.v<semver> e.g. memcached-operator.v0.0.1`
http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/local-storage-operator-metadata-container-v4.12.0.202211081106.p0.g9621dbf.assembly.stream-1/eb7a6164-8072-45c9-8c1b-1509785971c9/operator-metadata-linting-bundle-image-output.txt
I think this could be a common issue, so pr against master can cherry-pick to 4.12 branch later.
=> OCPBUGS-4346: fix naming convention

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Carry patch with a fix has been merged to 4.10: https://github.com/openshift/sig-storage-local-static-provisioner/pull/44.
Bump to the fixed version and vendor.
=> [release-4.10] OCPBUGS-2477: do not flag PV as cleaned in cache too early

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/cache/cache.go, vendor/sigs.k8s.io/sig-storage-local-static-provisioner/pkg/deleter/deleter.go
Carry patch with a fix has been merged to 4.11: https://github.com/openshift/sig-storage-local-static-provisioner/pull/43.
Bump to the fixed version and vendor.
=> [release-4.11] OCPBUGS-2476: do not flag PV as cleaned in cache too early

go.mod, vendor/modules.txt
This is intended to fix the following error caught in cachito:
```
$ go list -mod readonly -m all
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
```
CC @openshift/storage
=> STOR-1019: Pin k8s.io/dynamic-resource-allocation to v0.26.1

Dockerfile
Recent [update](https://github.com/openshift/local-storage-operator/pull/387/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3) bumped golang version in go.mod. CI passed due to ci-operator image replacement, but local builds now fail:
```
$ ./hack/sync_bundle -o quay.io/rbednar/test:lso -d quay.io/rbednar/test:diskmaker -b quay.io/rbednar/test:bundle -i quay.io/rbednar/test:index bundle
.
.
.
=> ERROR [builder 4/4] RUN make build-diskmaker                                                                                                                                                                                                                    310.9s
------ …
```
=> bump builder image golang to 1.19

examples/olm/catalog-create-subscribe.yaml
`HACKING.md` suggests to run the following command to install LSO:
```
~> oc create -f examples/olm/catalog-create-subscribe.yaml
```
However it doesn't have expected effect because afterwards:
```
$ oc describe catalogsource -n openshift-local-storage
...
Status:
Message:  couldn't ensure registry server - error ensuring pod: : error creating new pod: localstorage-operator-manifests-: pods "localstorage-operator-manifests-ts4np" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "registry-server" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "registry-server" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "registry-server" must set …
```
=> OCPBUGS-12222: Fix permissions in `examples/olm/catalog-create-subscribe.yaml`

api/v1alpha1/localvolumediscovery_types.go, diskmaker/controllers/lvset/matcher_test.go, diskmaker/discovery/discovery.go, diskmaker/discovery/discovery_test.go, internal/diskutil.go
Adds multipath devices to discovery result.
Unrelated to discovery: we should expose multipath in console to improve user experience when creating `LocalVolumeSet` with multipath: https://github.com/openshift/console/pull/12723
cc @openshift/storage
=> OCPBUGS-10884: add multipath support for volume discovery

common/provisioner_utils.go, diskmaker/controllers/lvset/reconcile.go
Fixes https://issues.redhat.com/browse/OCPBUGS-15358
After the fix:
```
E0627 18:20:18.432300  423801 reconcile.go:371] "skipping provisioning of PV" err="found existing symlinks for device sdb in /mnt/local-storage"
E0627 18:20:18.432317  423801 reconcile.go:170] provisioning failed for sdb: found existing symlinks for device sdb in /mnt/local-storage
2023-06-27T18:20:18.432Z        ERROR   controller/controller.go:329    Reconciler error        {"controller": "localvolumeset", "controllerGroup": "local.storage.openshift.io", "controllerKind": "LocalVolumeSet", "LocalVolumeSet": {"name":"example","name
space":"openshift-local-storage"}, "namespace": "openshift-local-storage", "name": "example", "reconcileID": "cb41a2ae-d354-409b-a87b-afbc7dc39239", "error": "could not provision disk: …
```
=> OCPBUGS-15358: Improve logging existing symlinks

config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
`nodeSelector` should be present in majority of LocalVolume, so add it to the example.
=> OCPBUGS-16595: Add nodeSelector to sample LocalVolume CR

config/manifests/stable/image-references
So it is mirrored in disconnected environments.
`relatedImages` will be also populated by ART pipeline with the diskmaker, kube-rbac-proxy and the operator image itself. Let's hope the pipeline will keep the mustgather image there.
cc @openshift/storage
=> OCPBUGS-17131: Add mustgather to relatedImages

diskmaker/controllers/lv/reconcile.go, diskmaker/controllers/lv/reconcile_test.go, internal/diskutil.go, internal/diskutil_test.go
Prefer wwn, scsi and nvme device symlinks first.
Fixes https://issues.redhat.com/browse/OCPBUGS-16745
Note fore reviewers - I know this is slower than processing `/dev/disk/by-id` exactly once but I have benchmarked and evaluated various approaches.
One of the more faster solution is using a prefixtree (or a trie):
```
preferredPatterns := []string{"wwn", "scsi", "nvme",  ""}
for _, pattern := range preferredPatterns {
preferrdPaths := tree.FindKeys(pattern)
for _, path := range preferrdPaths {
matchPath, err := matchSymlink(path)
if err != nil {
return "", err
}
if matchPath != "" {
return matchPath, nil
}
}
}
```
I was using "github.com/beevik/prefixtree" library for that and is generally 30-40% faster. Not sure how much it matters in actual practice though.
=> OCPBUGS-16745: prefer wwn, scsi and nvme devices

Dockerfile.mustgather
Follow up PR from https://github.com/openshift/secrets-store-csi-driver-operator/pull/9#discussion_r1288132661
The builder image is not really necessary for the must-gather image.
/cc @openshift/storage @jsafrane
=> remove unnecessary builder image from Dockerfile.mustgather

config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
If `relatedImages:` is present in a CSV, ART pipeline does not add more images to it.
Add a dummy env. var, so ART pipeline sees that the must-gather image is used and adds it to `relatedImages` automatically.
=> OCPBUGS-17131: Fix related images again

diskmaker/controllers/deleter/reconcile.go, diskmaker/controllers/lv/reconcile.go, diskmaker/controllers/lvset/reconcile.go
There are multiple unrelated smaller fixes (one per commit) which should clean up diskmaker logs which was full of misleading messages like:
```
426 04:19:50.027715  786279 controller_runtime_utils.go:77] "could not get provisioner configmap" err="ConfigMap \"local-provisioner\" not found" name="local-provisioner" namespace="local-disks"                                         
2023-04-26T04:19:50.027Z        ERROR   controller/controller.go:326    Reconciler error        {"controller": "localvolumeset", "controllerGroup": "local.storage.openshift.io", "controllerKind": "LocalVolumeSet", "LocalVolumeSet":
{"name":"local-disks","namespace":"local-disks"} 
```
```
I0426 04:20:30.012965  786279 reconcile.go:70] Deleting PVs through sig storage deleter
```
(Trace log level is used)
```
I0919 …
```
=> OCPBUGS-12887: remove misleading messages from diskmaker-manager log

docs/deploy-with-olm.md
Valid for latest under OCP 4.13
=> fix: Correct link to downstream product documentation

api/v1/localvolume_types.go, config/manifests/stable/local-volumes.crd.yaml, diskmaker/controllers/lv/diskconfig.go, diskmaker/controllers/lv/reconcile.go, diskmaker/controllers/lv/reconcile_test.go, internal/diskutil.go, internal/diskutil_test.go, test-framework/testutils/volume_util.go, test-framework/testutils/volume_util_linux.go, test-framework/testutils/volume_util_unsupported.go, test-framework/utils.go
An exampe of LocalVolume with new option set:
```
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
name: "local-disks"
namespace: "openshift-local-storage"
spec:
nodeSelector:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/hostname
operator: In
values:
- ip-10-0-7-58.us-west-2.compute.internal
storageClassDevices:
- storageClassName: "local-sc"
forceWipeDevicesAndDestroyAllData: true
volumeMode: Filesystem
fsType: xfs
devicePaths:
- /dev/loop0
```
`forceWipeDevicesAndDestroyAllData` is optional. The default is false. If it is set explicitly to true (as in example above), corresponding `devicePaths` will be wiped out before exposing as PVs. Wiping must happen only once, along with creating symlink in `/mnt/local-storage/<storageClassName>/`.
=> STOR-1377: Add option `forceWipeDevicesAndDestroyAllData` to wipe local volumes

hack/scripts/quick_reset.sh
mkfs has a limit of 16TB, let's use mkfs.xfs to avoid failure on large volumes.
=> OCPBUGS-22250: Use mkfs.xfs in quick_reset.sh

must-gather/gather
To save time when running the LSO MG, the collection must-gather commands can be executed in parallel.
We can compare the MG runtime with my fix and the regular image. I built a private image `quay.io/oviner/ocs-must-gather:lso_mg`
```
time oc adm must-gather --image=quay.io/oviner/ocs-must-gather:lso_mg
```
=> Running must-gather commands in background

Dockerfile.mustgather, must-gather/gather, must-gather/gather-common.sh
Use MUST_GATHER_SINCE and MUST_GATHER_SINCE_TIME env. vars to limit log collection. They are set by `oc adm must-gather --since` or `--since-time`.
Tested by:
```
oc adm must-gather --image=quay.io/jsafrane/scratch:mg4 --since-time=2024-04-10T10:16:25.762Z
oc adm must-gather --image=quay.io/jsafrane/scratch:mg4 --since=1h
```
This PR contains a partial copy of https://github.com/openshift/must-gather/blob/a175e0178104f4f794828c02245cd2de896cef0e/collection-scripts/common.sh, I haven't found a way how to share the script nicely.
=> STOR-1827: Limit must-gather log collection by timestamps

Dockerfile.mustgather
Update to must-gather image
followup to https://github.com/openshift/local-storage-operator/pull/485
=> OCPBUGS-34323: Use must-gather image

assets/templates/localmetrics/prometheus-rule.yaml, pkg/diskmaker/controllers/lvset/reconcile.go, pkg/localmetrics/localmetrics.go
This will warn users when the LocalVolumeSet has a deletion timestamp older than 24 hours.
=> OCPBUGS-34420: Add metric and alert for LocalVolumeSet deletion

pkg/common/provisioner_utils.go, pkg/common/symlink_utils.go, pkg/diskmaker/controllers/lv/reconcile.go, pkg/diskmaker/controllers/lvset/reconcile.go
https://issues.redhat.com/browse/OCPBUGS-44879
- **OCPBUGS-44879: remove symlink dir when LV / LVS is deleted**
https://issues.redhat.com/browse/OCPBUGS-45095
- **OCPBUGS-45095: optimize requeue time when LV / LVS is deleted**
=> OCPBUGS-44879, OCPBUGS-45095: remove symlink dir, optimize requeue time

config/manifests/stable/local-storage-operator.clusterserviceversion.yaml, docs/deploy-with-olm.md
and update doc to use the term "control plane nodes" instead of "master nodes".
=> OCPBUGS-48098: Rename `master` branch to `main`

pkg/diskmaker/controllers/lv/reconcile.go, pkg/diskmaker/controllers/lvset/reconcile.go
If users delete LV before deleting PVC LSO will put a finalizer on LV and start a cleanup job for the volume but won't reconcile again automatically to finish the cleanup and remove the finalizer and PV. Because of this a bulk deletion of resources with `oc delete` can hang forever, unless something else triggers reconcile.
This PR is basically a partial cherry-pick of https://github.com/openshift/local-storage-operator/commit/bd326bf1b3eba6af0632546b2fa5983671e4c68a to add a fast re-queue specifically for this case.
With this patch we can delete the resources in any order without getting into what appears to be a "stuck" state:
```
$ oc create -f /tmp/resources.yaml
namespace/mariadb-db created
localvolume.local.storage.openshift.io/local-disks created …
```
=> OCPBUGS-48322: Fast requeue when LV / LVS deletion is blocked

pkg/common/names.go, pkg/common/resourceapply.go, pkg/controllers/localvolume/api_updater.go, pkg/controllers/localvolume/localvolume_controller.go, pkg/controllers/localvolumeset/api_updater.go, pkg/controllers/localvolumeset/localvolumeset_controller.go, pkg/controllers/localvolumeset/localvolumeset_controller_test.go
- Remove duplicated consts unify use the common package consts
- Add OwnerKindLabel for both localvolume/localvolumeset owned storageClasses, which could be helpful to avoid conflict reconcile storageClasses(remove) if the lv and lvset the same name.
- Fix the cleanup storageclass for localvolumeset deletion.
**Test records**
- Verify that both localvolume/localvolumeset owned storageClasses could be removed after they are deleted.
```console
wangpenghao@pewang-mac  ~  oc get sc --show-labels
NAME                PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE     LABELS
gp2-csi             ebs.csi.aws.com                Delete          WaitForFirstConsumer   true                   3h41m   <none>
gp3-csi (default)   ebs.csi.aws.com …
```
=> OCPBUGS-51038: fix cleanup storageclass for localvolumeset

config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
Enable readOnlyFileSystem in the operator for security concerns.
Recommended for all containers running in kubernetes.
=> STOR-2126: Enable readOnlyFileSystem

config/manifests/local-storage-operator.package.yaml, config/manifests/stable/local-storage-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/STOR-2408
=> STOR-2408: Bump OLM metadata to 4.20

assets/templates/diskmaker-discovery-daemonset.yaml, assets/templates/diskmaker-manager-daemonset.yaml, config/manifests/stable/local-storage-operator.clusterserviceversion.yaml, config/manifests/stable/network-policy-allow-egress-to-api-server.yaml, config/manifests/stable/network-policy-allow-egress-to-dns.yaml, config/manifests/stable/network-policy-allow-ingress-to-diskmaker-metrics.yaml, config/manifests/stable/network-policy-allow-ingress-to-operator-metrics.yaml, config/manifests/stable/network-policy-default-deny-all.yaml
https://issues.redhat.com/browse/STOR-2331
Manually verified:
1) These NetworkPolicy manifests are deployed to the same namespace as the operator (`openshift-local-storage`) when the operator is installed
2) local-storage-operator, diskmaker-discovery, and diskmaker-manager pods have the correct labels + policies applied. Used nmap to verify expected ingress ports are accessible and others are not.
3) A standalone pod in the namespace without any labels applied can not reach the outside world (deny-all policy is in effect).
/cc @openshift/storage @mpatlasov
=> STOR-2331: Add NetworkPolicy manifests for LSO

pkg/internal/diskutil.go, pkg/internal/diskutil_test.go
https://issues.redhat.com/browse/OCPBUGS-61988
Some scsi devices produce symlink names that are not unique enough to
avoid conflicts, which can result in the symlink pointing to a different
device after reboot.
This commit encodes a preference for scsi identifiers that are more
stable (scsi-3*) over identifiers known to be less stable (scsi-0*)
using the same preference order that `lsscsi` uses.
=> OCPBUGS-61988: prioritize scsi symlink paths by uniqueness
